### PR TITLE
Minor fix for a bug

### PR DESCRIPTION
**Pull request by BachToTheFuture**
I don't have Haiku around me to test it, but it should fix issue #48.

### CODE REVIEW

**Comment by humdingerb** [comment]
Doesn't fix it completely.
Going from "Week" to "Day" works, going from "Week" to "Today" does not, it still shows the week (situation as described in #48).

Also, clicking on "Day" always changes the calendar to today. When you were on any other day, it shouldn't change the day at all, just switch from e.g. Week view to Day view.

**Comment by bach5000** [comment]
@humdingerb I will work on the fix right away in my spare time, but I have to apply to several universities with deadlines in the upcoming weeks, so I won't be much of a help, at least for two weeks.
I'm really sorry about this :(

**Comment by humdingerb** [comment]
No worries. It's not that bugs fix themselves over time. They'll still be here when you're back... :)

**Comment by ModeenF** [comment]
Can we close this? #48 are fixed in another merge.

**Comment by humdingerb** [comment]
Indeed. Thanks for the heads-up.

**Pull request closed without merging**
