### PR TITLE
Save current tab and mode, keyboard shortcuts

### PR DESCRIPTION
**Pull request by JadedCtrl**
Just saves the current tab (week/month/day) and mode (agenda/show hidden), and adds keyboard shortcuts to the menubar items for Add/Edit/Delete-- changing Delete from ALT-D to ALT-T, to be a little more in-line with Tracker. Also adds an "Add event" item to the event list's context menu when nothing is selected.

### CODE REVIEW

**Comment by humdingerb** [comment]
A few remarks:
* I think most Haiku apps call'em "Settings..." not "Preferences...". Practically there's no real difference between settings, preferences and options, we should just pick one and try to have everybody use it. I'd take "Settings" over "Preferences" and have the latter reserved for the panels under Dekbar's "Preferences".
* "Remove event..." doesn't need the ellipsis. The alert popping up doesn't count as real window. :)
* The menu items of the Event menu and the context menu should be named the same. I'm not sure if I prefer to include the "event", i.e. "Add event..." instead of just "Add...". After all, the top menu item already says "Event" and the context menu is invoked on an event.     
Whatever you decide, the other menus ("Category" and "View") should follow the same philosophy.
* The context menu says "Delete...", the Events menu "Remove...".  Since the tag is [Deleted], it should say "Delete" everywhere.
* I'd add the "Add..." item also to the context menu when clicking on an event, not only when clicking in the empty space of the list. Some very busy people may have so many events, they don't find some free space...    
Maybe renaming "Add" to "New" shows that you create a new event, and isn't confused to "add" to the currently selected.
* Don't forget to re-generate the catkeys when you're abuot done with new/changed GUI strings.
* Remember you can use the same B_TRANSLATION_CONTEXT when dealing with identical menu items (main menu bar & context menu) to avoid duplicated translations.

**Comment by JadedCtrl** [comment]
Made those changes, thanks! The consistency looks nice, and ALT-N works better with "New" than "Add," too :P

I might wait on updating catkeys if that seems good, I'd like to work on #105 and something else first.

**Comment by humdingerb** [comment]
Very good. Only the "Settings" window still says "Preferences" :)

**Comment by JadedCtrl** [comment]
Oh heck, got it now! xD

**Comment by humdingerb** [comment]
Thanks

**Pull request merged**
