### PR TITLE
Toggle event view buttons

### PR DESCRIPTION
**Pull request by malbx**
The application does not provide any visual indication of which event view is selected.  The proposed change toggles the event view buttons based on the users selection.

### CODE REVIEW

**Comment by humdingerb** [comment]
Works! The code looks good to me, but I'm no real dev, so...

**Comment by humdingerb** [comment]
Just noticed: it'd be nice if those three options - day, week, agenda - where toggled with a checkmark in the "View" menu.

**Comment by malbx** [comment]
> Just noticed: it'd be nice if those three options - day, week, agenda - where toggled with a checkmark in the "View" menu.

Thank you for the suggestion.  I have made the change so that the "View" menu is updated appropriately.

**Comment by malbx** [comment]
Changes have been made to resolve #65.  The state of the view button will be maintained after a date is selected from the calendar.

**Pull request merged**
